import json
import random
import re
from datetime import datetime

import httpx

import utils


class ScriptRunner:

    def __init__(self, client: httpx.Client, page: str, script: str, _cf_chl_opt: dict, _cf_chl_ctx: dict) -> None:
        self.client = client
        self.page = page
        self.script = self.clean_script(script)
        self._cf_chl_opt = _cf_chl_opt
        self._cf_chl_ctx = _cf_chl_ctx

    @staticmethod
    def clean_script(script: str) -> str:
        script = script.replace("aanotafontaa", "Times New Roman")
        return script

    def get_result(self) -> str:
        result = json.loads(utils.magic_eval({
            "url": str(self.client.base_url),
            "userAgent": self.client.headers["User-Agent"],
            "page": self.page,
            "script": self.script,
            "_cf_chl_opt": self._cf_chl_opt,
            "_cf_chl_ctx": self._cf_chl_ctx
        }))
        outer_height = random.randint(1000, 1200)
        outer_width = random.randint(2000, 2200)
        inter_height = random.randint(800, 1000)
        inter_width = random.randint(1800, 2000)
        for key, value in result.items():
            if key.isdigit():
                if "a" in value:
                    if isinstance(value["a"], dict):
                        if str(self.client.base_url) in value["a"]:
                            value["a"] = {
                                "0": ["innerHeight", "innerWidth", "length", "mozInnerScreenX", "mozInnerScreenY", "pageXOffset", "pageYOffset", "scrollMaxX", "scrollMaxY", "scrollX", "scrollY", "n.maxTouchPoints"],
                                "1": ["d.DOCUMENT_POSITION_DISCONNECTED", "d.ELEMENT_NODE", "d.childElementCount"],
                                "2": ["d.ATTRIBUTE_NODE", "d.DOCUMENT_POSITION_PRECEDING"],
                                "3": ["d.TEXT_NODE"],
                                "4": ["d.CDATA_SECTION_NODE", "d.DOCUMENT_POSITION_FOLLOWING"],
                                "5": ["d.ENTITY_REFERENCE_NODE"],
                                "6": ["d.ENTITY_NODE"],
                                "7": ["d.PROCESSING_INSTRUCTION_NODE"],
                                "8": ["d.COMMENT_NODE", "d.DOCUMENT_POSITION_CONTAINS"],
                                "9": ["d.DOCUMENT_NODE", "d.nodeType"],
                                "10": ["d.DOCUMENT_TYPE_NODE"],
                                "11": ["d.DOCUMENT_FRAGMENT_NODE"],
                                "12": ["n.hardwareConcurrency", "d.NOTATION_NODE"],
                                "16": ["d.DOCUMENT_POSITION_CONTAINED_BY"],
                                "32": ["d.DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC"],
                                str(outer_height): ["outerHeight"],
                                str(outer_width): ["outerWidth"],
                                "N": ["AbortController", "AbortSignal", "AbstractRange", "AggregateError", "AnalyserNode", "Animation", "AnimationEffect", "AnimationEvent", "AnimationPlaybackEvent", "AnimationTimeline", "ArrayBuffer", "Attr", "Audio", "AudioBuffer", "AudioBufferSourceNode", "AudioContext", "AudioDestinationNode", "AudioListener", "AudioNode", "AudioParam", "AudioParamMap", "AudioProcessingEvent", "AudioScheduledSourceNode", "AudioWorklet", "AudioWorkletNode", "AuthenticatorAssertionResponse", "AuthenticatorAttestationResponse", "AuthenticatorResponse", "BarProp", "BaseAudioContext", "BeforeUnloadEvent", "BigInt", "BigInt64Array", "BigUint64Array", "BiquadFilterNode", "Blob", "BlobEvent", "Boolean", "BroadcastChannel", "ByteLengthQueuingStrategy", "CDATASection", "CSS2Properties", "CSSAnimation", "CSSConditionRule", "CSSCounterStyleRule", "CSSFontFaceRule", "CSSFontFeatureValuesRule", "CSSFontPaletteValuesRule", "CSSGroupingRule", "CSSImportRule", "CSSKeyframeRule",
                                      "CSSKeyframesRule", "CSSLayerBlockRule", "CSSLayerStatementRule", "CSSMediaRule", "CSSMozDocumentRule", "CSSNamespaceRule", "CSSPageRule", "CSSRule", "CSSRuleList", "CSSStyleDeclaration", "CSSStyleRule", "CSSStyleSheet", "CSSSupportsRule", "CSSTransition", "Cache", "CacheStorage", "CanvasCaptureMediaStream", "CanvasGradient", "CanvasPattern", "CanvasRenderingContext2D", "CaretPosition", "ChannelMergerNode", "ChannelSplitterNode", "CharacterData", "Clipboard", "ClipboardEvent", "CloseEvent", "Comment", "CompositionEvent", "ConstantSourceNode", "ConvolverNode", "CountQueuingStrategy", "Credential", "CredentialsContainer", "Crypto", "CryptoKey", "CustomElementRegistry", "CustomEvent", "DOMException", "DOMImplementation", "DOMMatrix", "DOMMatrixReadOnly", "DOMParser", "DOMPoint", "DOMPointReadOnly", "DOMQuad", "DOMRect", "DOMRectList", "DOMRectReadOnly", "DOMRequest", "DOMStringList", "DOMStringMap", "DOMTokenList", "DataTransfer", "DataTransferItem",
                                      "DataTransferItemList", "DataView", "Date", "DelayNode", "DeviceMotionEvent", "DeviceOrientationEvent", "Directory", "Document", "DocumentFragment", "DocumentTimeline", "DocumentType", "DragEvent", "DynamicsCompressorNode", "Element", "ElementInternals", "Error", "ErrorEvent", "EvalError", "Event", "EventCounts", "EventSource", "EventTarget", "File", "FileList", "FileReader", "FileSystem", "FileSystemDirectoryEntry", "FileSystemDirectoryReader", "FileSystemEntry", "FileSystemFileEntry", "FinalizationRegistry", "Float32Array", "Float64Array", "FocusEvent", "FontFace", "FontFaceSet", "FontFaceSetLoadEvent", "FormData", "FormDataEvent", "Function", "GainNode", "Gamepad", "GamepadButton", "GamepadEvent", "GamepadHapticActuator", "GamepadPose", "Geolocation", "GeolocationCoordinates", "GeolocationPosition", "GeolocationPositionError", "HTMLAllCollection", "HTMLAnchorElement", "HTMLAreaElement", "HTMLAudioElement", "HTMLBRElement", "HTMLBaseElement",
                                      "HTMLBodyElement", "HTMLButtonElement", "HTMLCanvasElement", "HTMLCollection", "HTMLDListElement", "HTMLDataElement", "HTMLDataListElement", "HTMLDetailsElement", "HTMLDialogElement", "HTMLDirectoryElement", "HTMLDivElement", "HTMLDocument", "HTMLElement", "HTMLEmbedElement", "HTMLFieldSetElement", "HTMLFontElement", "HTMLFormControlsCollection", "HTMLFormElement", "HTMLFrameElement", "HTMLFrameSetElement", "HTMLHRElement", "HTMLHeadElement", "HTMLHeadingElement", "HTMLHtmlElement", "HTMLIFrameElement", "HTMLImageElement", "HTMLInputElement", "HTMLLIElement", "HTMLLabelElement", "HTMLLegendElement", "HTMLLinkElement", "HTMLMapElement", "HTMLMarqueeElement", "HTMLMediaElement", "HTMLMenuElement", "HTMLMetaElement", "HTMLMeterElement", "HTMLModElement", "HTMLOListElement", "HTMLObjectElement", "HTMLOptGroupElement", "HTMLOptionElement", "HTMLOptionsCollection", "HTMLOutputElement", "HTMLParagraphElement", "HTMLParamElement", "HTMLPictureElement",
                                      "HTMLPreElement", "HTMLProgressElement", "HTMLQuoteElement", "HTMLScriptElement", "HTMLSelectElement", "HTMLSlotElement", "HTMLSourceElement", "HTMLSpanElement", "HTMLStyleElement", "HTMLTableCaptionElement", "HTMLTableCellElement", "HTMLTableColElement", "HTMLTableElement", "HTMLTableRowElement", "HTMLTableSectionElement", "HTMLTemplateElement", "HTMLTextAreaElement", "HTMLTimeElement", "HTMLTitleElement", "HTMLTrackElement", "HTMLUListElement", "HTMLUnknownElement", "HTMLVideoElement", "HashChangeEvent", "Headers", "History", "IDBCursor", "IDBCursorWithValue", "IDBDatabase", "IDBFactory", "IDBIndex", "IDBKeyRange", "IDBObjectStore", "IDBOpenDBRequest", "IDBRequest", "IDBTransaction", "IDBVersionChangeEvent", "IIRFilterNode", "IdleDeadline", "Image", "ImageBitmap", "ImageBitmapRenderingContext", "ImageData", "InputEvent", "Int16Array", "Int32Array", "Int8Array", "InternalError", "IntersectionObserver", "IntersectionObserverEntry", "KeyEvent",
                                      "KeyboardEvent", "KeyframeEffect", "Location", "Lock", "LockManager", "MIDIAccess", "MIDIConnectionEvent", "MIDIInput", "MIDIInputMap", "MIDIMessageEvent", "MIDIOutput", "MIDIOutputMap", "MIDIPort", "Map", "MathMLElement", "MediaCapabilities", "MediaCapabilitiesInfo", "MediaDeviceInfo", "MediaDevices", "MediaElementAudioSourceNode", "MediaEncryptedEvent", "MediaError", "MediaKeyError", "MediaKeyMessageEvent", "MediaKeySession", "MediaKeyStatusMap", "MediaKeySystemAccess", "MediaKeys", "MediaList", "MediaMetadata", "MediaQueryList", "MediaQueryListEvent", "MediaRecorder", "MediaRecorderErrorEvent", "MediaSession", "MediaSource", "MediaStream", "MediaStreamAudioDestinationNode", "MediaStreamAudioSourceNode", "MediaStreamEvent", "MediaStreamTrack", "MediaStreamTrackAudioSourceNode", "MediaStreamTrackEvent", "MessageChannel", "MessageEvent", "MessagePort", "MimeType", "MimeTypeArray", "MouseEvent", "MouseScrollEvent", "MutationEvent", "MutationObserver",
                                      "MutationRecord", "NamedNodeMap", "Navigator", "Node", "NodeFilter", "NodeIterator", "NodeList", "Notification", "Number", "Object", "OfflineAudioCompletionEvent", "OfflineAudioContext", "OfflineResourceList", "OffscreenCanvas", "OffscreenCanvasRenderingContext2D", "Option", "OscillatorNode", "PageTransitionEvent", "PaintRequest", "PaintRequestList", "PannerNode", "Path2D", "Performance", "PerformanceEntry", "PerformanceEventTiming", "PerformanceMark", "PerformanceMeasure", "PerformanceNavigation", "PerformanceNavigationTiming", "PerformanceObserver", "PerformanceObserverEntryList", "PerformancePaintTiming", "PerformanceResourceTiming", "PerformanceServerTiming", "PerformanceTiming", "PeriodicWave", "PermissionStatus", "Permissions", "Plugin", "PluginArray", "PointerEvent", "PopStateEvent", "PopupBlockedEvent", "ProcessingInstruction", "ProgressEvent", "Promise", "PromiseRejectionEvent", "Proxy", "PublicKeyCredential", "RTCCertificate",
                                      "RTCDTMFSender", "RTCDTMFToneChangeEvent", "RTCDataChannel", "RTCDataChannelEvent", "RTCDtlsTransport", "RTCIceCandidate", "RTCPeerConnection", "RTCPeerConnectionIceEvent", "RTCRtpReceiver", "RTCRtpSender", "RTCRtpTransceiver", "RTCSessionDescription", "RTCStatsReport", "RTCTrackEvent", "RadioNodeList", "Range", "RangeError", "ReadableByteStreamController", "ReadableStream", "ReadableStreamBYOBReader", "ReadableStreamBYOBRequest", "ReadableStreamDefaultController", "ReadableStreamDefaultReader", "ReferenceError", "RegExp", "Request", "ResizeObserver", "ResizeObserverEntry", "ResizeObserverSize", "Response", "SVGAElement", "SVGAngle", "SVGAnimateElement", "SVGAnimateMotionElement", "SVGAnimateTransformElement", "SVGAnimatedAngle", "SVGAnimatedBoolean", "SVGAnimatedEnumeration", "SVGAnimatedInteger", "SVGAnimatedLength", "SVGAnimatedLengthList", "SVGAnimatedNumber", "SVGAnimatedNumberList", "SVGAnimatedPreserveAspectRatio", "SVGAnimatedRect",
                                      "SVGAnimatedString", "SVGAnimatedTransformList", "SVGAnimationElement", "SVGCircleElement", "SVGClipPathElement", "SVGComponentTransferFunctionElement", "SVGDefsElement", "SVGDescElement", "SVGElement", "SVGEllipseElement", "SVGFEBlendElement", "SVGFEColorMatrixElement", "SVGFEComponentTransferElement", "SVGFECompositeElement", "SVGFEConvolveMatrixElement", "SVGFEDiffuseLightingElement", "SVGFEDisplacementMapElement", "SVGFEDistantLightElement", "SVGFEDropShadowElement", "SVGFEFloodElement", "SVGFEFuncAElement", "SVGFEFuncBElement", "SVGFEFuncGElement", "SVGFEFuncRElement", "SVGFEGaussianBlurElement", "SVGFEImageElement", "SVGFEMergeElement", "SVGFEMergeNodeElement", "SVGFEMorphologyElement", "SVGFEOffsetElement", "SVGFEPointLightElement", "SVGFESpecularLightingElement", "SVGFESpotLightElement", "SVGFETileElement", "SVGFETurbulenceElement", "SVGFilterElement", "SVGForeignObjectElement", "SVGGElement", "SVGGeometryElement", "SVGGradientElement",
                                      "SVGGraphicsElement", "SVGImageElement", "SVGLength", "SVGLengthList", "SVGLineElement", "SVGLinearGradientElement", "SVGMPathElement", "SVGMarkerElement", "SVGMaskElement", "SVGMatrix", "SVGMetadataElement", "SVGNumber", "SVGNumberList", "SVGPathElement", "SVGPatternElement", "SVGPoint", "SVGPointList", "SVGPolygonElement", "SVGPolylineElement", "SVGPreserveAspectRatio", "SVGRadialGradientElement", "SVGRect", "SVGRectElement", "SVGSVGElement", "SVGScriptElement", "SVGSetElement", "SVGStopElement", "SVGStringList", "SVGStyleElement", "SVGSwitchElement", "SVGSymbolElement", "SVGTSpanElement", "SVGTextContentElement", "SVGTextElement", "SVGTextPathElement", "SVGTextPositioningElement", "SVGTitleElement", "SVGTransform", "SVGTransformList", "SVGUnitTypes", "SVGUseElement", "SVGViewElement", "Screen", "ScreenOrientation", "ScriptProcessorNode", "ScrollAreaEvent", "SecurityPolicyViolationEvent", "Selection", "Set", "ShadowRoot", "SharedArrayBuffer",
                                      "SharedWorker", "SourceBuffer", "SourceBufferList", "SpeechSynthesis", "SpeechSynthesisErrorEvent", "SpeechSynthesisEvent", "SpeechSynthesisUtterance", "SpeechSynthesisVoice", "StaticRange", "StereoPannerNode", "Storage", "StorageEvent", "StorageManager", "String", "StyleSheet", "StyleSheetList", "SubmitEvent", "SubtleCrypto", "Symbol", "SyntaxError", "Text", "TextDecoder", "TextDecoderStream", "TextEncoder", "TextEncoderStream", "TextMetrics", "TextTrack", "TextTrackCue", "TextTrackCueList", "TextTrackList", "TimeEvent", "TimeRanges", "TrackEvent", "TransformStream", "TransformStreamDefaultController", "TransitionEvent", "TreeWalker", "TypeError", "U2F", "UIEvent", "URIError", "URL", "URLSearchParams", "Uint16Array", "Uint32Array", "Uint8Array", "Uint8ClampedArray", "VTTCue", "VTTRegion", "ValidityState", "VideoPlaybackQuality", "VisualViewport", "WaveShaperNode", "WeakMap", "WeakRef", "WeakSet", "WebGL2RenderingContext", "WebGLActiveInfo",
                                      "WebGLBuffer", "WebGLContextEvent", "WebGLFramebuffer", "WebGLProgram", "WebGLQuery", "WebGLRenderbuffer", "WebGLRenderingContext", "WebGLSampler", "WebGLShader", "WebGLShaderPrecisionFormat", "WebGLSync", "WebGLTexture", "WebGLTransformFeedback", "WebGLUniformLocation", "WebGLVertexArrayObject", "WebKitCSSMatrix", "WebSocket", "WheelEvent", "Window", "Worker", "Worklet", "WritableStream", "WritableStreamDefaultController", "WritableStreamDefaultWriter", "XMLDocument", "XMLHttpRequest", "XMLHttpRequestEventTarget", "XMLHttpRequestUpload", "XMLSerializer", "XPathEvaluator", "XPathExpression", "XPathResult", "XSLTProcessor", "addEventListener", "alert", "atob", "blur", "btoa", "cancelAnimationFrame", "cancelIdleCallback", "captureEvents", "clearInterval", "clearTimeout", "close", "confirm", "createImageBitmap", "decodeURI", "decodeURIComponent", "dispatchEvent", "dump", "encodeURI", "encodeURIComponent", "escape", "eval", "fetch", "find", "focus",
                                      "getComputedStyle", "getDefaultComputedStyle", "getSelection", "isFinite", "isNaN", "matchMedia", "moveBy", "moveTo", "mozRTCIceCandidate", "mozRTCPeerConnection", "mozRTCSessionDescription", "open", "parseFloat", "parseInt", "postMessage", "print", "prompt", "queueMicrotask", "releaseEvents", "removeEventListener", "reportError", "requestAnimationFrame", "requestIdleCallback", "resizeBy", "resizeTo", "scroll", "scrollBy", "scrollByLines", "scrollByPages", "scrollTo", "setInterval", "setResizable", "setTimeout", "sizeToContent", "stop", "structuredClone", "unescape", "updateCommands", "webkitURL", "n.getGamepads", "n.javaEnabled", "n.mozGetUserMedia", "n.registerProtocolHandler", "n.requestMIDIAccess", "n.requestMediaKeySystemAccess", "n.sendBeacon", "n.taintEnabled", "n.vibrate", "d.addEventListener", "d.adoptNode", "d.append", "d.appendChild", "d.captureEvents", "d.caretPositionFromPoint", "d.clear", "d.cloneNode", "d.close",
                                      "d.compareDocumentPosition", "d.contains", "d.createAttribute", "d.createAttributeNS", "d.createCDATASection", "d.createComment", "d.createDocumentFragment", "d.createElement", "d.createElementNS", "d.createEvent", "d.createExpression", "d.createNSResolver", "d.createNodeIterator", "d.createProcessingInstruction", "d.createRange", "d.createTextNode", "d.createTreeWalker", "d.dispatchEvent", "d.elementFromPoint", "d.elementsFromPoint", "d.enableStyleSheetsForSet", "d.evaluate", "d.execCommand", "d.exitFullscreen", "d.exitPointerLock", "d.getAnimations", "d.getElementById", "d.getElementsByClassName", "d.getElementsByName", "d.getElementsByTagName", "d.getElementsByTagNameNS", "d.getRootNode", "d.getSelection", "d.hasChildNodes", "d.hasFocus", "d.hasStorageAccess", "d.importNode", "d.insertBefore", "d.isDefaultNamespace", "d.isEqualNode", "d.isSameNode", "d.lookupNamespaceURI", "d.lookupPrefix", "d.mozCancelFullScreen", "d.mozSetImageElement",
                                      "d.normalize", "d.open", "d.prepend", "d.queryCommandEnabled", "d.queryCommandIndeterm", "d.queryCommandState", "d.queryCommandSupported", "d.queryCommandValue", "d.querySelector", "d.querySelectorAll", "d.releaseCapture", "d.releaseEvents", "d.removeChild", "d.removeEventListener", "d.replaceChild", "d.replaceChildren", "d.requestStorageAccess", "d.write", "d.writeln"],
                                "L": ["Array"],
                                "o": ["Atomics", "CSS", "Intl", "JSON", "Math", "Reflect", "WebAssembly", "applicationCache", "caches", "clientInformation", "console", "crypto", "customElements", "document", "external", "frameElement", "frames", "globalThis", "history", "indexedDB", "localStorage", "location", "locationbar", "menubar", "navigator", "netscape", "parent", "performance", "personalbar", "screen", "scrollbars", "self", "sessionStorage", "speechSynthesis", "statusbar", "toolbar", "top", "u2f", "visualViewport", "window", "n.clipboard", "n.credentials", "n.geolocation", "n.locks", "n.mediaCapabilities", "n.mediaDevices", "n.mediaSession", "n.mimeTypes", "n.permissions", "n.plugins", "n.storage", "d.activeElement", "d.anchors", "d.applets", "d.body", "d.childNodes", "d.children", "d.defaultView", "d.documentElement", "d.embeds", "d.firstChild", "d.firstElementChild", "d.fonts", "d.forms", "d.head", "d.images", "d.implementation", "d.lastChild", "d.lastElementChild", "d.links",
                                      "d.location", "d.plugins", "d.scripts", "d.scrollingElement", "d.styleSheetSets", "d.styleSheets", "d.timeline"],
                                "Infinity": ["Infinity"],
                                "x": ["InstallTrigger", "onabort", "onabsolutedeviceorientation", "onafterprint", "onanimationcancel", "onanimationend", "onanimationiteration", "onanimationstart", "onauxclick", "onbeforeinput", "onbeforeprint", "onbeforeunload", "onblur", "oncanplay", "oncanplaythrough", "onchange", "onclick", "onclose", "oncontextmenu", "oncuechange", "ondblclick", "ondevicemotion", "ondeviceorientation", "ondrag", "ondragend", "ondragenter", "ondragexit", "ondragleave", "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied", "onended", "onerror", "onfocus", "onformdata", "ongamepadconnected", "ongamepaddisconnected", "ongotpointercapture", "onhashchange", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup", "onlanguagechange", "onload", "onloadeddata", "onloadedmetadata", "onloadstart", "onlostpointercapture", "onmessage", "onmessageerror", "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout", "onmouseover", "onmouseup",
                                      "onmozfullscreenchange", "onmozfullscreenerror", "onoffline", "ononline", "onpagehide", "onpageshow", "onpause", "onplay", "onplaying", "onpointercancel", "onpointerdown", "onpointerenter", "onpointerleave", "onpointermove", "onpointerout", "onpointerover", "onpointerup", "onpopstate", "onprogress", "onratechange", "onrejectionhandled", "onreset", "onresize", "onscroll", "onscrollend", "onsecuritypolicyviolation", "onseeked", "onseeking", "onselect", "onselectionchange", "onselectstart", "onslotchange", "onstalled", "onstorage", "onsubmit", "onsuspend", "ontimeupdate", "ontoggle", "ontransitioncancel", "ontransitionend", "ontransitionrun", "ontransitionstart", "onunhandledrejection", "onunload", "onvolumechange", "onwaiting", "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart", "onwebkittransitionend", "onwheel", "opener", "d.all", "d.currentScript", "d.doctype", "d.fullscreenElement", "d.lastStyleSheetSet",
                                      "d.mozFullScreenElement", "d.nextSibling", "d.nodeValue", "d.onabort", "d.onafterscriptexecute", "d.onanimationcancel", "d.onanimationend", "d.onanimationiteration", "d.onanimationstart", "d.onauxclick", "d.onbeforeinput", "d.onbeforescriptexecute", "d.onblur", "d.oncanplay", "d.oncanplaythrough", "d.onchange", "d.onclick", "d.onclose", "d.oncontextmenu", "d.oncopy", "d.oncuechange", "d.oncut", "d.ondblclick", "d.ondrag", "d.ondragend", "d.ondragenter", "d.ondragexit", "d.ondragleave", "d.ondragover", "d.ondragstart", "d.ondrop", "d.ondurationchange", "d.onemptied", "d.onended", "d.onerror", "d.onfocus", "d.onformdata", "d.onfullscreenchange", "d.onfullscreenerror", "d.ongotpointercapture", "d.oninput", "d.oninvalid", "d.onkeydown", "d.onkeypress", "d.onkeyup", "d.onload", "d.onloadeddata", "d.onloadedmetadata", "d.onloadstart", "d.onlostpointercapture", "d.onmousedown", "d.onmouseenter", "d.onmouseleave", "d.onmousemove", "d.onmouseout",
                                      "d.onmouseover", "d.onmouseup", "d.onmozfullscreenchange", "d.onmozfullscreenerror", "d.onpaste", "d.onpause", "d.onplay", "d.onplaying", "d.onpointercancel", "d.onpointerdown", "d.onpointerenter", "d.onpointerleave", "d.onpointerlockchange", "d.onpointerlockerror", "d.onpointermove", "d.onpointerout", "d.onpointerover", "d.onpointerup", "d.onprogress", "d.onratechange", "d.onreadystatechange", "d.onreset", "d.onresize", "d.onscroll", "d.onscrollend", "d.onsecuritypolicyviolation", "d.onseeked", "d.onseeking", "d.onselect", "d.onselectionchange", "d.onselectstart", "d.onslotchange", "d.onstalled", "d.onsubmit", "d.onsuspend", "d.ontimeupdate", "d.ontoggle", "d.ontransitioncancel", "d.ontransitionend", "d.ontransitionrun", "d.ontransitionstart", "d.onvisibilitychange", "d.onvolumechange", "d.onwaiting", "d.onwebkitanimationend", "d.onwebkitanimationiteration", "d.onwebkitanimationstart", "d.onwebkittransitionend", "d.onwheel", "d.ownerDocument",
                                      "d.parentElement", "d.parentNode", "d.pointerLockElement", "d.previousSibling", "d.rootElement", "d.textContent"],
                                "NaN": ["NaN"],
                                "false": ["closed", "fullScreen", "n.webdriver", "d.fullscreen", "d.hidden", "d.mozFullScreen"],
                                "true": ["crossOriginIsolated", "isSecureContext", "n.cookieEnabled", "n.onLine", "n.pdfViewerEnabled", "d.fullscreenEnabled", "d.isConnected", "d.mozFullScreenEnabled"],
                                "1.25": ["devicePixelRatio"],
                                "u": ["event", "undefined"],
                                str(self.client.base_url): ["origin"],
                                "-9": ["screenLeft", "screenTop", "screenX", "screenY"],
                                "Mozilla": ["n.appCodeName"],
                                "Netscape": ["n.appName"],
                                "5.0 (Windows)": ["n.appVersion"],
                                "en-US": ["n.language"],
                                "en-US,en": ["n.languages"],
                                "Windows NT 10.0; Win64; x64": ["n.oscpu"],
                                "Win32": ["n.platform"],
                                "Gecko": ["n.product"],
                                self.client.headers["User-Agent"]: ["n.userAgent"],
                                "about:blank": ["d.URL", "d.documentURI"],
                                "": ["d.adoptedStyleSheets"],
                                str(self.client.base_url) : ["d.baseURI"],
                                "UTF-8": ["d.characterSet", "d.charset", "d.inputEncoding"],
                                "BackCompat": ["d.compatMode"],
                                "text/html": ["d.contentType"],
                                "off": ["d.designMode"],
                                str(self.client.base_url).replace("https://", ""): ["d.domain"],
                                str(datetime.now().strftime("%m/%d/%Y %H:%M:%S")): ["d.lastModified"],
                                "#document": ["d.nodeName"],
                                "uninitialized": ["d.readyState"],
                                "visible": ["d.visibilityState"]
                            }
                    if isinstance(value["a"], str):
                        if value["a"].startswith("Ninjas"):
                            value["a"] = "Ninjas>pirates,anonymous/_[_[0]]/<" + str(self.client.base_url) + "/cdn-cgi/challeng"
                if "p" in value and "s" in value and "is" in value:
                    if isinstance(value["is"], list):
                        value["is"] = ["name", "", "status", "", "closed", False, "length", 0, "innerWidth", inter_width, "innerHeight", inter_height, "scrollX", 0, "pageXOffset", 0, "scrollY", 0, "pageYOffset", 0, "screenLeft", -7, "screenTop", -7, "screenX", -7, "screenY", -7, "outerWidth", outer_width, "outerHeight", outer_height, "mozInnerScreenX", 0, "mozInnerScreenY", 84.80000305175781, "devicePixelRatio", 1.25, "scrollMaxX", 0, "scrollMaxY", 120, "fullScreen", False, "origin", str(self.client.base_url), "crossOriginIsolated", True, "isSecureContext", True, "NaN", None, "Infinity", None, "_cf_chl_done_ran", True, "prefix", "cf"]
                if "aw" in value and "ah" in value:
                    if isinstance(value["aw"], int) and isinstance(value["ah"], int):
                        img = re.search('\"(/img/.*?)\",', self.script).group(1)
                        img = utils.path_join("/cdn-cgi/challenge-platform/h/", self._cf_chl_opt["cFPWv"], img)
                        value["aw"], value["ah"] = utils.get_image_size(self.client, img)
        return result
